/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/$system'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemSubRouteImport } from './routes/$system.$sub'

const SystemRoute = SystemRouteImport.update({
  id: '/$system',
  path: '/$system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSubRoute = SystemSubRouteImport.update({
  id: '/$sub',
  path: '/$sub',
  getParentRoute: () => SystemRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$system': typeof SystemRouteWithChildren
  '/$system/$sub': typeof SystemSubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$system': typeof SystemRouteWithChildren
  '/$system/$sub': typeof SystemSubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$system': typeof SystemRouteWithChildren
  '/$system/$sub': typeof SystemSubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$system' | '/$system/$sub'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$system' | '/$system/$sub'
  id: '__root__' | '/' | '/$system' | '/$system/$sub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SystemRoute: typeof SystemRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$system': {
      id: '/$system'
      path: '/$system'
      fullPath: '/$system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$system/$sub': {
      id: '/$system/$sub'
      path: '/$sub'
      fullPath: '/$system/$sub'
      preLoaderRoute: typeof SystemSubRouteImport
      parentRoute: typeof SystemRoute
    }
  }
}

interface SystemRouteChildren {
  SystemSubRoute: typeof SystemSubRoute
}

const SystemRouteChildren: SystemRouteChildren = {
  SystemSubRoute: SystemSubRoute,
}

const SystemRouteWithChildren =
  SystemRoute._addFileChildren(SystemRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SystemRoute: SystemRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
